#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const { spawn } = require('child_process');

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i += 1) {
    const key = argv[i];
    if (!key.startsWith('--')) continue;
    const value = argv[i + 1];
    out[key.slice(2)] = value;
    i += 1;
  }
  return out;
}

function parsePrimitive(value) {
  const text = String(value || '').trim();
  if (text === 'true') return true;
  if (text === 'false') return false;
  if (text === 'null' || text === 'nil' || text === 'none') return null;
  if (/^-?\d+$/.test(text)) return Number.parseInt(text, 10);
  if (/^-?\d+\.\d+$/.test(text)) return Number.parseFloat(text);
  return text;
}

function collectWatchNamesFromSource(cwd) {
  const out = [];
  const sourcePath = path.join(cwd || process.cwd(), 'src', 'main.cpp');
  try {
    const content = fs.readFileSync(sourcePath, 'utf8');
    const re = /\b(?:int|double|float|bool|std::string)\s+([A-Za-z_]\w*)\s*(?:=|;)/g;
    let m = re.exec(content);
    while (m) {
      const name = String(m[1] || '').trim();
      if (name && !out.includes(name)) out.push(name);
      m = re.exec(content);
    }
  } catch {
    // ignore source parse failures
  }
  return out;
}

function detectUserBreakpointSpec(cwd) {
  const sourcePath = path.join(cwd || process.cwd(), 'src', 'main.cpp');
  try {
    const content = fs.readFileSync(sourcePath, 'utf8');
    const lines = content.split(/\r?\n/);
    for (let i = 0; i < lines.length; i += 1) {
      const line = String(lines[i] || '');
      if (line.includes('sleep_for(') || line.includes('std::this_thread::sleep_for(')) {
        return `${sourcePath}:${i + 1}`;
      }
    }
    for (let i = 0; i < lines.length; i += 1) {
      const line = String(lines[i] || '');
      if (line.includes('while (true)') || line.includes('while(true)')) {
        return `${sourcePath}:${i + 1}`;
      }
    }
  } catch {
    // ignore source parse failures
  }
  return 'main';
}

function toGdbValue(value) {
  if (value === true) return '1';
  if (value === false) return '0';
  if (value === null || value === undefined) return '0';
  if (typeof value === 'number') return String(value);
  return JSON.stringify(String(value));
}

function parseFrame(doneLine) {
  const fileMatch = doneLine.match(/fullname="([^"]+)"/) || doneLine.match(/file="([^"]+)"/);
  const lineMatch = doneLine.match(/line="(\d+)"/);
  const fnMatch = doneLine.match(/func="([^"]+)"/);
  return {
    file: fileMatch ? fileMatch[1] : '',
    line: lineMatch ? Number.parseInt(lineMatch[1], 10) : 0,
    function: fnMatch ? fnMatch[1] : '',
  };
}

function parseVariables(doneLine) {
  const vars = {};
  const tupleRe = /\{([^{}]*)\}/g;
  let tuple = tupleRe.exec(doneLine);
  while (tuple) {
    const block = tuple[1];
    const nameMatch = block.match(/name="((?:[^"\\]|\\.)*)"/);
    const valueMatch = block.match(/value="((?:[^"\\]|\\.)*)"/);
    const name = nameMatch ? nameMatch[1].replace(/\\"/g, '"') : '';
    if (name && !name.startsWith('__') && valueMatch) {
      const rawValue = valueMatch[1].replace(/\\"/g, '"');
      vars[name] = parsePrimitive(rawValue);
    }
    tuple = tupleRe.exec(doneLine);
  }
  return vars;
}

function decodeMiStreamText(line) {
  const m = line.match(/^[~@&]"((?:[^"\\]|\\.)*)"$/);
  if (!m) return '';
  const decoded = m[1]
    .replace(/\\n/g, '\n')
    .replace(/\\t/g, '\t')
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, '\\');
  // Keep terminal usable: hide repetitive interrupt noise generated by -exec-interrupt.
  if (decoded.includes('Program received signal SIGINT')) return '';
  if (decoded.includes('Signal        Stop      Print   Pass to program Description')) return '';
  if (decoded.includes('SIGINT        ')) return '';
  if (decoded.includes('Breakpoint ')) return '';
  if (decoded.includes('std::this_thread::sleep_for')) return '';
  if (decoded.trim() === '') return '';
  return decoded;
}

function parseFirstFrameLevelWithFile(doneLine) {
  const frameTupleRe = /frame=\{([^{}]*)\}/g;
  let tuple = frameTupleRe.exec(doneLine);
  let firstLevel = null;
  while (tuple) {
    const block = tuple[1];
    const levelMatch = block.match(/level="(\d+)"/);
    if (!levelMatch) {
      tuple = frameTupleRe.exec(doneLine);
      continue;
    }
    const level = Number.parseInt(levelMatch[1], 10);
    if (firstLevel === null) firstLevel = level;
    const fullMatch = block.match(/fullname="([^"]+)"/) || block.match(/file="([^"]+)"/);
    const file = fullMatch ? fullMatch[1] : '';
    // Prefer source frames over system/libc frames.
    if (file && !file.startsWith('/lib/') && !file.startsWith('/usr/lib/')) {
      return level;
    }
    tuple = frameTupleRe.exec(doneLine);
  }
  if (firstLevel !== null) return firstLevel;
  const m = doneLine.match(/level="(\d+)"/);
  if (m) return Number.parseInt(m[1], 10);
  return 0;
}

function parseDoneValue(doneLine) {
  const m = String(doneLine || '').match(/value="((?:[^"\\]|\\.)*)"/);
  if (!m) return undefined;
  return parsePrimitive(m[1].replace(/\\"/g, '"'));
}

class GdbWrapper {
  constructor({ programPath, varsPipePath, controlPipePath, cwd }) {
    this.programPath = path.resolve(programPath);
    this.varsPipePath = path.resolve(varsPipePath);
    this.controlPipePath = path.resolve(controlPipePath);
    this.cwd = cwd || process.cwd();
    this.token = 1;
    this.pending = new Map();
    this.controlQueue = [];
    this.stream = fs.createWriteStream(this.varsPipePath, { flags: 'a', encoding: 'utf8' });
    this.running = false;
    this.stopped = false;
    this.waitingInterrupt = false;
    this.tickTimer = null;
    this.watchNames = collectWatchNamesFromSource(this.cwd);
    this.breakpointSpec = detectUserBreakpointSpec(this.cwd);
    this.useInterruptSampling = true;
  }

  start() {
    this.startControlReader();
    this.gdb = spawn('gdb', ['--interpreter=mi2', '--quiet', '--nx'], {
      cwd: this.cwd,
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    const stdoutRl = readline.createInterface({ input: this.gdb.stdout });
    stdoutRl.on('line', (line) => this.onGdbLine(String(line || '').trim()));
    this.gdb.stderr.on('data', (chunk) => {
      // Keep stderr consumed to avoid blocking.
      void chunk;
    });
    this.gdb.on('exit', () => {
      this.cleanup();
      process.exit(0);
    });

    this.bootstrap().catch(() => {
      this.cleanup();
      process.exit(1);
    });
  }

  startControlReader() {
    const reopen = () => {
      const controlStream = fs.createReadStream(this.controlPipePath, { encoding: 'utf8' });
      const rl = readline.createInterface({ input: controlStream });
      rl.on('line', (line) => {
        const text = String(line || '').trim();
        if (!text) return;
        try {
          const payload = JSON.parse(text);
          if (payload && payload.type === 'set_value' && payload.name) {
            this.controlQueue.push(payload);
          }
        } catch {
          // ignore malformed line
        }
      });
      rl.on('close', () => {
        setTimeout(reopen, 10);
      });
      rl.on('error', () => {
        setTimeout(reopen, 200);
      });
    };
    reopen();
  }

  send(cmd) {
    const token = this.token++;
    const full = `${token}${cmd}\n`;
    return new Promise((resolve, reject) => {
      this.pending.set(String(token), { resolve, reject });
      this.gdb.stdin.write(full);
    });
  }

  onGdbLine(line) {
    if (!line) return;
    const streamText = decodeMiStreamText(line);
    if (streamText) {
      process.stdout.write(streamText);
      return;
    }
    const match = line.match(/^(\d+)\^(.*)$/);
    if (match) {
      const [, token, payload] = match;
      const pending = this.pending.get(token);
      if (!pending) return;
      this.pending.delete(token);
      if (payload.startsWith('error')) pending.reject(new Error(payload));
      else pending.resolve(`^${payload}`);
      return;
    }
    if (line.startsWith('*running')) {
      this.running = true;
      this.stopped = false;
      return;
    }
    if (line.startsWith('*stopped')) {
      this.running = false;
      this.stopped = true;
      if (line.includes('reason="exited-normally"') || line.includes('reason="exited-signalled"')) {
        this.cleanup();
        process.exit(0);
      }
      this.onStopped().catch(() => {
        this.cleanup();
        process.exit(1);
      });
      return;
    }
    if (!line.match(/^[~@&^*=+]/) && !line.startsWith('(gdb)')) {
      process.stdout.write(line + '\n');
    }
  }

  async bootstrap() {
    await this.send('-gdb-set pagination off');
    await this.send('-gdb-set confirm off');
    await this.send('-gdb-set mi-async on');
    await this.send('-gdb-set disable-randomization off');
    await this.send(`-file-exec-and-symbols "${this.programPath}"`);
    try {
      await this.send(`-break-insert ${this.breakpointSpec}`);
      this.useInterruptSampling = false;
    } catch {
      // Fall back to interrupt-based sampling when breakpoint insertion fails.
      this.useInterruptSampling = true;
    }
    await this.send('-exec-run');
    this.running = true;

    if (this.useInterruptSampling) {
      this.tickTimer = setInterval(async () => {
        if (!this.running || this.stopped || this.waitingInterrupt) return;
        this.waitingInterrupt = true;
        try {
          await this.send('-exec-interrupt');
        } catch {
          // ignore
        } finally {
          this.waitingInterrupt = false;
        }
      }, 1000);
    }
  }

  async onStopped() {
    let frameResp = await this.send('-stack-info-frame');
    let frame = parseFrame(frameResp);
    if (!frame.file || !frame.line) {
      try {
        const framesResp = await this.send('-stack-list-frames');
        const level = parseFirstFrameLevelWithFile(framesResp);
        await this.send(`-stack-select-frame ${level}`);
        frameResp = await this.send('-stack-info-frame');
        frame = parseFrame(frameResp);
      } catch {
        // keep current frame if frame selection fails
      }
    }

    let varsResp = '';
    try {
      varsResp = await this.send('-stack-list-variables --all-values');
    } catch {
      varsResp = await this.send('-stack-list-variables --simple-values');
    }
    const vars = parseVariables(varsResp);

    if (Object.keys(vars).length === 0 && this.watchNames.length > 0) {
      for (const name of this.watchNames) {
        try {
          const valueResp = await this.send(`-data-evaluate-expression ${name}`);
          const value = parseDoneValue(valueResp);
          if (value !== undefined) vars[name] = value;
        } catch {
          // ignore symbols not in scope
        }
      }
    }

    while (this.controlQueue.length > 0) {
      const cmd = this.controlQueue.shift();
      const name = String(cmd.name || '').trim();
      if (!name) continue;
      const valueExpr = toGdbValue(cmd.value);
      try {
        await this.send(`-gdb-set var ${name}=${valueExpr}`);
        vars[name] = cmd.value;
      } catch {
        // ignore invalid writes
      }
    }

    const payload = {
      type: 'vars.snapshot',
      vars,
      frame,
    };
    this.stream.write(`${JSON.stringify(payload)}\n`);

    await this.send('-exec-continue');
    this.running = true;
    this.stopped = false;
  }

  cleanup() {
    if (this.tickTimer) {
      clearInterval(this.tickTimer);
      this.tickTimer = null;
    }
    try {
      this.stream.end();
    } catch {
      // ignore
    }
    try {
      this.gdb?.kill('SIGTERM');
    } catch {
      // ignore
    }
  }
}

const args = parseArgs(process.argv.slice(2));
const programPath = String(args.program || '').trim();
const varsPipePath = String(args['vars-pipe'] || '').trim();
const controlPipePath = String(args['control-pipe'] || '').trim();
if (!programPath || !varsPipePath || !controlPipePath) {
  process.stderr.write('usage: autowrx_cpp_gdb_wrapper.js --program <path> --vars-pipe <path> --control-pipe <path>\n');
  process.exit(2);
}

const wrapper = new GdbWrapper({
  programPath,
  varsPipePath,
  controlPipePath,
  cwd: process.cwd(),
});
wrapper.start();
